title: "Barbara Draghi"
description: "Research • Projects • Coffee & Learn"
url: "https://barbaradraghi.github.io"
baseurl: ""
markdown: kramdown
permalink: pretty
theme: null

plugins:
  - jekyll-seo-tag

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: page
